version: "2"

services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret cookie here'
    networks:
      - front-tier

  rabbitmq-management:
    image: rabbitmq:management
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=password

networks:
  front-tier:
